blank_issues_enabled: false
contact_links:
  - name: Support request
    url: https://github.com/goldenpathtechnologies/gatsby-awesome-pagination/discussions
    about: Please ask and answer support requests in the GitHub Discussions page of this project
