name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Generate release notes
        run: |
          mkdir ./tmp
          git log -1 --pretty=format:"%b" > ./tmp/release_notes

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./tmp/release_notes
          token: ${{secrets.GH_TOKEN}}
