name: Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - .gitattributes
      - CHANGELOG.md
      - README.md
      - LICENSE
      - CODE_OF_CONDUCT.md
      - package.json
    tags-ignore:
      - "**"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          npx \
          -p @semantic-release/npm \
          -p @semantic-release/exec \
          -p @semantic-release/git \
          -p @semantic-release/commit-analyzer \
          -p @semantic-release/release-notes-generator \
          -p @semantic-release/changelog \
          -p conventional-changelog-conventionalcommits \
          semantic-release
